# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Print env variables
      env:
        REGION: ${{vars.ENV_REGION}}
      run: |
        echo "Just checking env variable $REGION"

    - name: Print secret variables
      env:
        DUMMY_SECRET: ${{secrets.SECRET_USER}}
      run: |
        echo "Just checking secret variable ${{secrets.SECRET_USER}}"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
